### ISSUE TITLE
Invalid array buffer length

### ISSUE THREAD

**Issue by gleidsonhenriques** [Comcast/Speed-testJS#102]
Hi all,

 I'm trying to start some tests with this code and i'm getting the error below:

 RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:23:15)
    at allocate (buffer.js:98:12)
    at new Buffer (buffer.js:53:12)
    at DownloadController.getDownload (/root/Speed-testJS/controllers/DownloadController.js:56:30)
    at Layer.handle [as handle_request] (/root/Speed-testJS/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/Speed-testJS/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/Speed-testJS/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/Speed-testJS/node_modules/express/lib/router/layer.js:95:5)

    I'm testing a Gigabit Network. Below are some specs and environment of the server:
    
    Distro: Ubuntu 16.04.2 LTS
    NodeJS: v4.2.6
    NPM: 3.5.2
    Memory:
                  total        used        free      shared  buff/cache   available
Mem:           1999         222        1676           5         101        1639

  If anyone knows what's going on and may help me i'll be really glad full.

**Comment by rotosonic** [comment]
Can you try to increase the memory for your node instance....
https://stackoverflow.com/questions/34356012/how-to-increase-nodejs-default-memory

**Comment by gleidsonhenriques** [comment]
Hi @rotosonic ... thanks for your help.

But no deal. I've tried with 1024,2048,4096. But always got same error.

It's intriguing that's this error is showing only with me. You guys are testing Gigabit ?

If yes, could you please share server environment and specs ?

**Comment by gleidsonhenriques** [comment]
Hi,

  Just for clarification. After increase memory of the server. The problem is gone.

**Comment by hackzilla** [comment]
@gleidsonhenriques What did you increase your server memory to?
